name: neucon
channels:
  # You can use the TUNA mirror to speed up the installation if you are in mainland China.
  # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7.9
  - pytorch=1.6.0
  - torchvision=0.7.0
  - cudatoolkit=10.2
  - ipython
  - tqdm
  - numba
  - sparsehash  # dependency for torchsparse
  - pip
  - pip:
    - -r requirements.txt
    - git+https://github.com/mit-han-lab/torchsparse.git
